#!/bin/bash

set -e

# shellcheck disable=SC1091
[ -f .env ] && . .env

[ ! -d node_modules ] && npm ci

scripts/kill-ganache-cli

# Default test mnemonic 
mnemonic="opera tired scrap latin mosquito wall file diesel mad aware one merry"

# test-runner script will pass --quiet param as $1
npx ganache-cli --fork "$NODE_URL" --host 0.0.0.0 --mnemonic "$mnemonic" -e 100000 $1 &
