name: VSP token and vVSP Pool
on: [pull_request]

jobs:
  vsp-and-vvsp-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12]
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          submodules: true
      - run: cat "${GITHUB_WORKSPACE}/.github/env.properties" >> $GITHUB_ENV
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Run npm install with node v${{ matrix.node }}
        run: npm install
      - name: Running VSP token tests
        env:
          NODE_URL: ${{env.NODE_URL}}
        run: npm test "test/vsp.js"
      - name: Running vVSP pool tests
        env:
          NODE_URL: ${{env.NODE_URL}}
        run: npm test "test/vvsp-eth.js"
      - name: Running vVSP auctions tests
        env:
          NODE_URL: ${{env.NODE_URL}}
        run: npm test "test/vvsp-auctions.js"        